# Generated by Django 2.2.6 on 2019-10-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='priority',
            field=models.IntegerField(default=2),
        ),
    ]
