# Generated by Django 2.2.6 on 2019-10-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militaria', '0002_auto_20191028_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='max',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='min',
            field=models.IntegerField(default=70),
        ),
    ]
