# Generated by Django 2.2.6 on 2019-11-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militaria', '0003_auto_20191028_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='weight',
            field=models.IntegerField(default=3),
        ),
    ]
